'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowRight,Search,BookOpen,ExternalLink} from 'lucide-react';
import {ScorePolicy} from '@/components/score-panel';
import {Header,Footer,useLanguage} from '@/components/shell';
import {docsCopy} from '@/lib/docs-copy';
import config from '@/lib/deployment.json';
const ids=['introduction','profile','scoring','limits','guarantees','lifecycle','capital','security','contracts'];
export default function Docs(){
 const {t,lang}=useLanguage();const c=docsCopy[lang];const [topic,setTopic]=useState('introduction');const [query,setQuery]=useState('');
 const titles=[c.overview,t.profile,t.score,c.limits,t.guarantees,c.life,t.pool,c.security,c.contracts];
 const index=Math.max(0,ids.indexOf(topic));
 useEffect(()=>{const sync=()=>{const id=location.hash.slice(1);if(ids.includes(id))setTopic(id)};sync();window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync)},[]);
 function navigate(id:string){setTopic(id);history.pushState(null,'','#'+id);document.getElementById('doc-title')?.focus();window.scrollTo({top:0,behavior:'instant'})}
 const sections=index===0?[{title:c.overview,body:c.intro},{title:t.network,body:c.status}]:index===1?[{title:t.step1,body:t.step1d},{title:t.network,body:t.publicNotice},{title:t.achievements,body:t.optionalEvidence}]:index===2?[]:index===3?[{title:c.limits,body:c.limitText},{title:c.allocated,body:c.automatic}]:index===4?[{title:t.step2,body:t.step2d},{title:c.allocated,body:c.automatic},{title:t.principled,body:t.guaranteeWarn}]:index===5?[{title:c.life,body:c.lifeText},{title:t.payments,body:t.step3d},{title:t.principled,body:t.guaranteeWarn}]:index===6?[{title:t.pool,body:c.poolText},{title:t.network,body:t.risk}]:index===7?[{title:c.security,body:c.securityText},{title:t.network,body:c.status}]:[];
 return <><Header/><main className="docs-layout"><aside className="docs-sidebar"><a href="/docs" className="docs-brand"><BookOpen size={19}/>{c.contents}</a><label className="docs-search"><Search size={16}/><input aria-label={c.search} placeholder={c.search} value={query} onChange={e=>setQuery(e.target.value)}/></label><span className="docs-group">DANK / MONAD</span><nav aria-label={c.contents}>{ids.map((id,i)=>titles[i].toLocaleLowerCase(lang).includes(query.toLocaleLowerCase(lang))&&<a key={id} href={'#'+id} aria-current={topic===id?'page':undefined} onClick={e=>{e.preventDefault();navigate(id)}}><span>{String(i+1).padStart(2,'0')}</span>{titles[i]}</a>)}</nav><a className="docs-enter" href="/app">{t.enter}<ArrowRight size={16}/></a></aside><article className="docs-article"><div className="docs-breadcrumb">{c.contents}<span>/</span>{titles[index]}</div><span className="eyebrow">DANK · MONAD TESTNET</span><h1 id="doc-title" tabIndex={-1}>{titles[index]}</h1><p className="docs-description">{index===0?t.docsLead:titles[index]+' · DANK'}</p><div className="docs-rule"/>{sections.map((s,i)=><section id={'section-'+i} key={i}><h2>{s.title}</h2><p>{s.body}</p></section>)}{index===2&&<section id="section-0"><ScorePolicy/></section>}{index===8&&<section id="section-0"><h2>Monad Testnet</h2>{[['Chain ID',String(config.chainId)],['RPC',config.rpc],['Gas','MON'],['Token','DANK Test USD · USD · 6 decimals']].map(([k,v])=><div className="data-row" key={k}><span>{k}</span><b>{v}</b></div>)}{[['DANK',config.protocol],['USD',config.token]].map(([label,address])=><div className="docs-address" key={label}><strong>{label}</strong><a href={config.explorer+'/address/'+address} target="_blank" rel="noreferrer">{address}<ExternalLink size={14}/></a></div>)}<p className="notice">{c.status}</p><a href="https://docs.monad.xyz/developer-essentials" target="_blank" rel="noreferrer" className="text-link">Monad Documentation ↗</a></section>}<div className="docs-pagination">{index>0?<a href={'#'+ids[index-1]} onClick={e=>{e.preventDefault();navigate(ids[index-1])}}><ArrowLeft size={17}/>{titles[index-1]}</a>:<span/>}{index<ids.length-1&&<a href={'#'+ids[index+1]} onClick={e=>{e.preventDefault();navigate(ids[index+1])}}>{titles[index+1]}<ArrowRight size={17}/></a>}</div></article><aside className="docs-toc"><span>{c.onPage}</span>{sections.map((s,i)=><a key={i} href={'#section-'+i} onClick={e=>{e.preventDefault();document.getElementById('section-'+i)?.scrollIntoView({behavior:'smooth'})}}>{s.title}</a>)}{sections.length===0&&<a href="#section-0" onClick={e=>{e.preventDefault();document.getElementById('section-0')?.scrollIntoView({behavior:'smooth'})}}>{titles[index]}</a>}<div className="docs-test-label">● {t.network}</div></aside></main><Footer/></>
}
