'use client';
import {useEffect,useState} from 'react';
import {LiquidityPanel} from '@/components/liquidity-panel';
import {WalletScore} from '@/components/score-panel';
import {docsCopy} from '@/lib/docs-copy';
import {supportAllocation} from '@/lib/support';
import {scoreCopy} from '@/lib/score-copy';
import {Header,Footer,useLanguage} from '@/components/shell';
import {ArrowUpRight,ArrowRight,Wallet,ShieldCheck,Trophy,Code2,Check,RefreshCw,ExternalLink,AlertTriangle,Plus,Users} from 'lucide-react';
import {config,read,write,connectWallet,signedApi,publicClient,tokenAbi,units,display,short,provider} from '@/lib/chain';
import {paymentPlan} from '@/lib/finance';
import {keccak256,toBytes,type Address} from 'viem';
type Tab='overview'|'achievements'|'borrow'|'guarantees'|'payments'|'pool'|'review';
const ZERO='0x'+'0'.repeat(64);
export default function Workspace(){
 const{t,lang}=useLanguage();const[tab,setTab]=useState<Tab>('overview');const[wallet,setWallet]=useState<Address|null>(null);const[demo,setDemo]=useState(false);const[role,setRole]=useState('borrower');const[busy,setBusy]=useState(false);const[toast,setToast]=useState('');const[hash,setHash]=useState('');
 const[member,setMember]=useState<any>(null);const[memberId,setMemberId]=useState(ZERO);const[chainLoan,setChainLoan]=useState<any>(null);const[chainSchedule,setChainSchedule]=useState<any[]>([]);const[balance,setBalance]=useState(0);const[liquidity,setLiquidity]=useState(0);const[phase,setPhase]=useState(0);const[backings,setBackings]=useState<any[]>([]);const[owner,setOwner]=useState(config.admin);
 const[records,setRecords]=useState<any>({application:null,evidence:[]});const[adminData,setAdminData]=useState<any>({applications:[],evidence:[]});
 const[amount,setAmount]=useState(80);const[months,setMonths]=useState(3);const[loanInput,setLoanInput]=useState('');const[consent,setConsent]=useState(false);const[payAmount,setPayAmount]=useState('');const[poolAmount,setPoolAmount]=useState('1000');
 const[demoLoan,setDemoLoan]=useState<any>(null);const[demoSupport,setDemoSupport]=useState(0);const[demoPaid,setDemoPaid]=useState(0);const[overdue,setOverdue]=useState(false);const[events,setEvents]=useState<string[]>([]);
 const[search,setSearch]=useState('');const[projects,setProjects]=useState<any[]>([]);const[chosen,setChosen]=useState<any>(null);const[proof,setProof]=useState('');const[note,setNote]=useState('');const[name,setName]=useState('');const[profile,setProfile]=useState('');const[reviewNote,setReviewNote]=useState('');const[lookup,setLookup]=useState<any>(null);
 const money=(v:number)=>new Intl.NumberFormat(lang,{maximumFractionDigits:2,minimumFractionDigits:2}).format(v);
 function notify(message:string){setToast(message);setTimeout(()=>setToast(''),6500)}
 async function run(fn:()=>Promise<void>){if(busy)return;setBusy(true);try{await fn()}catch(e){const message=(e as Error).message;notify(message==='WALLET_MISSING'?t.walletMissing:message==='NOT_DEPLOYED'?t.notDeployed:t.error+' '+message.slice(0,150))}finally{setBusy(false)}}
 async function refresh(address=wallet){if(!address||!config.deployed)return;const [id,cash,p,admin]=await Promise.all([read('memberOf',[address]),publicClient.readContract({address:config.token as Address,abi:tokenAbi,functionName:'balanceOf',args:[config.protocol as Address]}),read('phase'),read('owner')]);setMemberId(id);setLiquidity(display(cash));setPhase(Number(p));setOwner(admin);const bal=await publicClient.readContract({address:config.token as Address,abi:tokenAbi,functionName:'balanceOf',args:[address]});setBalance(display(bal));if(id!==ZERO){const m=await read('members',[id]);setMember(m);if(m[5]>0n){const l=await read('loans',[m[5]]);const s=await read('getSchedule',[m[5]]);setChainLoan({id:Number(m[5]),data:l});setChainSchedule(s)}else{setChainLoan(null);setChainSchedule([])}const ids=await read('getBackings',[id]);setBackings(await Promise.all(ids.map(async(id:bigint)=>({id:Number(id),data:await read('loans',[id]),overdue:await read('isOverdue',[id])}))));}else{setMember(null);setChainLoan(null);setBackings([])}}
 useEffect(()=>{const p=provider() as any;if(!p?.on)return;const changed=()=>{setWallet(null);setMember(null);setRecords({application:null,evidence:[]});setAdminData({applications:[],evidence:[]});setMemberId(ZERO);setChainLoan(null);setBackings([])};p.on('accountsChanged',changed);return()=>{p.removeListener?.('accountsChanged',changed);}},[]);
 useEffect(()=>{if(!config.deployed||!config.token||!config.protocol)return;let cancelled=false;Promise.all([publicClient.readContract({address:config.token,abi:tokenAbi,functionName:'balanceOf',args:[config.protocol]}),read('phase')]).then(([cash,p])=>{if(!cancelled){setLiquidity(display(cash));setPhase(Number(p))}}).catch(()=>{});return()=>{cancelled=true}},[]);
 async function connect(){await run(async()=>{const a=await connectWallet();setWallet(a);setDemo(false);await refresh(a)})}
 async function tx(fn:string,args:unknown[]=[],token=false){if(!wallet)throw new Error('WALLET_MISSING');const h=await write(wallet,fn,args,token);setHash(h);await refresh();notify(t.success);}
 async function tokenPayment(fn:string,args:unknown[],n:number){await tx('approve',[config.protocol,units(n)],true);await tx(fn,args)}
 function demoEvent(msg:string){setEvents(v=>[msg,...v].slice(0,8));notify(msg)}
 function startDemo(){setDemo(true);setTab('overview');setRole('borrower')}
 const isAdmin=wallet?.toLowerCase()===owner.toLowerCase()&&!demo;
 const limit=demo?80:member?display(member[2]):0;
 const points=demo?80:member?Number(member[1]):0;
 const blocked=demo?overdue:!!(member&&(Number(member[1])<80||Number(member[6])>0||backings.some(b=>b.overdue)));
 const loan=demo?demoLoan:chainLoan;
 const support=demo?supportAllocation(points,units(80),units(demoSupport),units(Math.max(0,(demoLoan?.amount||0)-demoSupport))):supportAllocation(points,member?.[3]||0n,member?.[4]||0n,lookup?BigInt(lookup.data[1])-BigInt(lookup.data[6]):0n);
 const supportText=docsCopy[lang];
 const preview=paymentPlan(amount,months);const total=preview.reduce((s,p)=>s+p.total,0);
 async function loadRecords(){if(wallet)setRecords(await signedApi(wallet,'read'))}
 async function findProjects(){await run(async()=>{const r=await fetch('/api/blitz?q='+encodeURIComponent(search));const data:any=await r.json();if(!r.ok)throw new Error(data.error);setProjects(data.projects)})}
 async function loadLoan(){await run(async()=>{if(!/^\d+$/.test(loanInput)||Number(loanInput)<1)throw new Error(t.loanId);setLookup({id:Number(loanInput),data:await read('loans',[BigInt(loanInput)]),guarantors:await read('getGuarantors',[BigInt(loanInput)])})})}
 useEffect(()=>{if(location.hash==='#pool')setTab('pool')},[]);
 const tabs:Tab[]=isAdmin?['overview','achievements','borrow','guarantees','payments','pool','review']:['overview','achievements','borrow','guarantees','payments','pool'];
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const ctl=new AbortController();Promise.resolve(context.registerTool({name:'estimate_dank_installments',description:'Read-only estimate for DANK testnet loan installments. Does not apply for credit or send transactions.',inputSchema:{type:'object',properties:{principal:{type:'number',minimum:10,maximum:1000},months:{type:'integer',minimum:1,maximum:12}},required:['principal','months'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:any)=>{const plan=paymentPlan(input.principal,input.months);return {simulation:true,apr:15,monthly:plan[0].total,total:plan.reduce((a,b)=>a+b.total,0)}}},{signal:ctl.signal})).catch(()=>{});return()=>ctl.abort()},[]);
 return <><Header/><main className="workspace"><div className="page-top"><div><span className="badge">{t.network} / USD</span><h1>{t.appTitle}</h1><p>{t.appLead}</p></div><div className="actions" style={{marginTop:10}}>{wallet?<button className="button" onClick={()=>{setWallet(null);setMember(null);setMemberId(ZERO);setChainLoan(null);setRecords({application:null,evidence:[]});setAdminData({applications:[],evidence:[]})}}>{short(wallet)} ×</button>:<button disabled={busy} className="button lime" onClick={connect}><Wallet size={18}/>{t.connect}</button>}<button className="button" onClick={startDemo}>{t.demo}<ArrowRight size={16}/></button></div></div>
 {demo?<div className="banner"><span><b>{t.demoMode}</b><br/><small>{t.demoNotice}</small></span><div className="actions" style={{margin:0,gap:10}}><label>{t.switchRole} <select className="field" value={role} onChange={e=>setRole(e.target.value)}><option value="borrower">{t.demoBorrower}</option><option value="guarantor">{t.demoGuarantor}</option></select></label><button className="button small" onClick={()=>{setDemoLoan(null);setDemoPaid(0);setDemoSupport(0);setOverdue(false);setEvents([])}}>{t.reset}</button><button className="icon-button" aria-label={t.disconnect} onClick={()=>setDemo(false)}>×</button></div></div>:<div className="banner"><span>{config.deployed?<><ShieldCheck size={15} style={{display:'inline',marginRight:8}}/>{t.contract}: <a className="mono" target="_blank" rel="noreferrer" href={config.explorer+'/address/'+config.protocol}>{short(config.protocol||'')} ↗</a></>:t.notDeployed}</span><span>{t.risk}</span></div>}
 <div className="tabs">{tabs.map(k=><button key={k} className={tab===k?'selected':''} onClick={()=>setTab(k)}>{t[k]}</button>)}</div>
 {tab==='overview'&&<><WalletScore address={demo?null:wallet}/><div className="stats"><div className="stat"><span>{t.score}</span><strong>{points}<small>pts</small></strong></div><div className="stat"><span>{t.available}</span><strong>{money(limit)}<small>USD</small></strong></div><div className="stat"><span>{t.status}</span><strong style={{fontSize:24}} className={blocked?'danger-text':'accent'}>{blocked?t.blocked:demo||member?t.approved:wallet?t.join:t.connect}</strong></div></div><div className="two-col"><section className="card"><h2>{t.activeLoan}</h2>{loan?<><div className="data-row"><span>{t.amount}</span><b>{money(demo?demoLoan.amount:display(chainLoan.data[1]))} USD</b></div><div className="data-row"><span>{t.status}</span><b>{demo?(demoLoan.active?t.active:t.pending):(chainLoan.data[5]>0n?t.active:t.pending)}</b></div><div className="form-actions"><button className="button lime" onClick={()=>setTab('payments')}>{t.payments}<ArrowUpRight size={16}/></button></div></>:<div className="empty"><Code2 size={32} style={{margin:'0 auto 15px'}}/><p>{t.noLoan}</p><button className="button lime" onClick={()=>setTab('borrow')}>{t.newLoan}<Plus size={16}/></button></div>}</section><section className="card"><h2>{t.profile}</h2><p>{t.walletHint}</p>{wallet&&!demo?<><p className="notice">{t.publicNotice}</p>{member?<p className="accent">{t.approved}</p>:<button className="button lime" disabled={busy||!config.deployed} onClick={()=>run(()=>tx('register'))}>{t.apply}</button>}</>:<><div className="data-row"><span><Trophy size={16} style={{display:'inline',marginRight:8}}/>{t.walletHistory} / {t.defiActivity}</span><b className="accent">≤ 80</b></div><div className="data-row"><span><Code2 size={16} style={{display:'inline',marginRight:8}}/>{t.achievements}</span><b className="accent">≤ 20</b></div><p className="notice">{t.memberOnly}</p></>}</section></div>{events.length>0&&<section className="card" style={{marginTop:24}}><h2>{t.activity}</h2>{events.map((e,i)=><div key={i} className="data-row"><span>{e}</span><Check size={16}/></div>)}</section>}</>}
 {tab==='achievements'&&<div className="two-col"><section className="card"><h2>{t.search}</h2><p>{t.optionalEvidence}</p><p>{t.searchHelp}</p><div className="actions" style={{marginTop:10}}><input aria-label={t.search} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')findProjects()}}/><button disabled={busy} className="button lime" onClick={findProjects}>{t.search}</button></div><div className="search-results">{projects.map(p=><div className="data-row" key={p.id}><div><b>{p.title}</b><small>{p.event.name} {p.is_winner?' / 🏆':''}</small></div><button className="button small" onClick={()=>{setChosen(p);setProof(p.github_url||'')}}>{t.select}</button></div>)}</div>{chosen&&<><h3 style={{marginTop:25}}>{chosen.title}</h3><label>{t.proof}</label><input type="url" value={proof} onChange={e=>setProof(e.target.value)}/><label>{t.note}</label><textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/><p>{t.evidenceHelp}</p><button disabled={busy||!wallet||demo||!proof} className="button lime" onClick={()=>run(async()=>{await signedApi(wallet!,'evidence',{projectId:chosen.id,title:chosen.title,proof,note});notify(t.evidenceSent);await loadRecords()})}>{t.submit}</button></>}</section><section className="card"><h2>{t.evidenceCount}</h2><p>{scoreCopy[lang].rule}</p>{demo?<>{[t.winner].map((e,i)=><div className="data-row" key={i}><span>{e}<small>{t.sample}</small></span><b className="accent">+{20}</b></div>)}</>:<><button className="button small" disabled={busy||!wallet} onClick={()=>run(loadRecords)}>{t.refresh}</button>{records.evidence.map((e:any)=><div className="data-row" key={e.id}><span>{e.title}<small>{e.event_slug}</small></span><span className="pill">{t[e.status as 'pending']}</span></div>)}{records.evidence.length===0&&<p className="empty">{t.empty}</p>}</>}</section></div>}
 {tab==='borrow'&&<div className="two-col"><section className="card"><h2>{t.newLoan}</h2><p>{t.eligibility}</p><label>{t.amount}: <strong className="accent">{money(amount)} USD</strong></label><input aria-label={t.amount} type="range" min="10" max="1000" step="10" value={amount} onChange={e=>setAmount(Number(e.target.value))}/><div className="form-grid"><div><label>{t.amount}</label><input type="number" min={10} max={1000} value={amount} onChange={e=>setAmount(Math.max(10,Math.min(1000,Number(e.target.value)||10)))}/></div><div><label>{t.months}</label><select className="field" value={months} onChange={e=>setMonths(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option key={i} value={i+1}>{i+1}</option>)}</select></div></div><div className="data-row"><span>{t.apr}</span><b>15%</b></div><div className="data-row"><span>{t.totalRepay}</span><b>{money(total)} USD</b></div><p className="notice">{t.pilotText}</p><button className="button lime" disabled={busy||blocked||!!loan||amount>limit||(!demo&&!member)||(demo&&role!=='borrower')} onClick={()=>{if(demo){setDemoLoan({amount,months,active:false});setDemoSupport(0);demoEvent(t.request);return}run(()=>tx('requestLoan',[units(amount),BigInt(months)]))}}>{t.create}<ArrowUpRight size={16}/></button>{loan&&<div className="notice"><p>{t.loanId}: <b>{demo?1:chainLoan.id}</b> — {t.shareLoan}</p><p>{t.coverage}: {money(demo?demoSupport:display(chainLoan.data[6]))} USD</p><button className="button small lime" disabled={busy||(demo?(demoLoan.active||demoSupport<demoLoan.amount||role!=='borrower'):chainLoan.data[5]>0n)} onClick={()=>{if(demo){setDemoLoan({...demoLoan,active:true});demoEvent(t.confirmLoan);return}run(()=>tx('activate',[BigInt(chainLoan.id)]))}}>{t.confirmLoan}</button></div>}</section><section className="card"><span className="eyebrow">{t.monthlyLabel}</span><div style={{fontSize:55,letterSpacing:-3,margin:'15px 0'}}>{money(preview[0].total)}<small className="muted" style={{marginLeft:10,letterSpacing:0}}>USD</small></div><h3>{t.plan}</h3><div className="table-wrap"><table><thead><tr><th>#</th><th>{t.due}</th><th>{t.principal}</th><th>{t.interest}</th></tr></thead><tbody>{preview.map(p=><tr key={p.number}><td>{p.number}</td><td>{new Date(p.due).toLocaleDateString(lang,{timeZone:'UTC'})}</td><td>{money(p.principal)}</td><td>{money(p.interest)}</td></tr>)}</tbody></table></div></section></div>}
 {tab==='guarantees'&&<div className="two-col"><section className="card"><h2>{t.guaranteeAction}</h2><p>{t.guaranteeWarn}</p><label>{t.loanId}</label><div className="actions" style={{marginTop:8}}><input type="number" min={1} value={demo?'1':loanInput} onChange={e=>{setLoanInput(e.target.value);setLookup(null)}} disabled={demo}/><button disabled={busy||demo||!config.deployed} className="button" onClick={loadLoan}>{t.refresh}</button></div>{lookup&&!demo&&<div className="notice"><b>#{lookup.id} · {money(display(lookup.data[1]))} USD</b><p>{t.coverage}: {money(display(lookup.data[6]))} USD</p><small className="mono">{t.memberId}: {short(lookup.data[0])}</small></div>}<div className="data-row"><span>{supportText.auto}</span><b>{money(display(support.scoreCap))} USD</b></div><div className="data-row"><span>{supportText.available}</span><b>{money(display(support.available))} USD</b></div><div className="notice"><b>{supportText.allocated}: {money(display(support.amount))} USD</b><p>{supportText.automatic}</p></div><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{t.accept}</label><div className="form-actions"><button className="button lime" disabled={busy||!consent||blocked||support.amount===0n||(!demo&&(!member||!lookup))||(demo&&(!demoLoan||demoLoan.active||demoSupport>0||role!=='guarantor'))} onClick={()=>{if(demo){setDemoSupport(display(support.amount));demoEvent(t.guaranteeAction);return}run(async()=>{const id=BigInt(lookup.id);const [freshMember,freshLoan]=await Promise.all([read('members',[memberId]),read('loans',[id])]);const allocation=supportAllocation(Number(freshMember[1]),freshMember[3],freshMember[4],BigInt(freshLoan[1])-BigInt(freshLoan[6]));if(allocation.amount!==support.amount){await refresh();setLookup(null);setConsent(false);throw new Error(t.refresh)}if(allocation.amount===0n)throw new Error(supportText.available+' = 0');await tx('guarantee',[id,allocation.amount]);setLookup(null);setConsent(false)})}}><ShieldCheck size={16}/>{t.confirm}</button></div></section><section className="card"><h2>{t.guarantees}</h2>{demo&&demoSupport>0?<><div className="data-row"><span>Builder #026</span><b>{money(demoSupport)} USD</b></div><p className={overdue?'notice danger-text':'notice'}>{overdue?t.blocked:t.active}</p></>:backings.length?backings.map(b=><div className="data-row" key={b.id}><span>#{b.id}<small>{money(display(b.data[1]))} USD</small></span><b className={b.overdue?'danger-text':''}>{b.overdue?t.late:t.active}</b></div>):<p className="empty">{t.empty}</p>}<p>{t.principled}</p></section></div>}
 {tab==='payments'&&<section className="card"><h2>{t.payments}</h2>{!loan?<p className="empty">{t.noLoan}</p>:demo?<><p>#{1} · {money(demoLoan.amount)} USD · {demoLoan.months} {t.months}</p>{demoLoan.active?<><div className="table-wrap"><table><thead><tr><th>#</th><th>{t.due}</th><th>{t.amount}</th><th>{t.status}</th></tr></thead><tbody>{paymentPlan(demoLoan.amount,demoLoan.months).map((p,i)=><tr key={i}><td>{i+1}</td><td>{new Date(p.due).toLocaleDateString(lang)}</td><td>{money(p.total)} USD</td><td>{i<demoPaid?t.paid:overdue&&i===demoPaid?t.late:t.pending}</td></tr>)}</tbody></table></div><div className="form-actions"><button disabled={role!=='borrower'} className="button lime" onClick={()=>{const next=demoPaid+1;setDemoPaid(next);setOverdue(false);demoEvent(t.paid);if(next>=demoLoan.months){setDemoLoan(null);setDemoPaid(0);setDemoSupport(0)}}}>{t.repay}</button><button className="button danger" disabled={overdue} onClick={()=>{setOverdue(true);demoEvent(t.blocked)}}>{t.simulate}</button></div></>:<p className="notice">{t.pending} — {t.guarantees}</p>}</>:<><p>#{chainLoan.id} · {money(display(chainLoan.data[2]))} USD</p><div className="table-wrap"><table><thead><tr><th>#</th><th>{t.due}</th><th>{t.principal}</th><th>{t.interest}</th><th>{t.status}</th></tr></thead><tbody>{chainSchedule.map((p,i)=><tr key={i}><td>{i+1}</td><td>{new Date(Number(p.due)*1000).toLocaleDateString(lang)}</td><td>{money(display(p.principal))}</td><td>{money(display(p.interest+p.penalty))}</td><td>{p.principal+p.interest+p.penalty===0n?t.paid:Number(p.due)*1000<Date.now()?t.late:t.pending}</td></tr>)}</tbody></table></div><label>{t.repayAmount}</label><input type="number" min={0.000001} step="0.000001" value={payAmount} onChange={e=>setPayAmount(e.target.value)}/><div className="form-actions"><button disabled={busy||!payAmount||chainLoan.data[5]===0n} className="button lime" onClick={()=>run(()=>tokenPayment('repay',[BigInt(chainLoan.id),units(payAmount)],Number(payAmount)))}>{t.repay}</button><button disabled={busy||chainLoan.data[5]===0n} className="button" onClick={()=>run(async()=>{const q=await read('payoff',[BigInt(chainLoan.id)]);await tx('approve',[config.protocol,q+10000n],true);await tx('repayAll',[BigInt(chainLoan.id),q+10000n])})}>{t.payFull}</button><button className="button" disabled={busy} onClick={()=>run(()=>refresh())}><RefreshCw size={16}/>{t.refresh}</button></div></>}</section>}
 {tab==='pool'&&<div className="two-col"><LiquidityPanel wallet={demo?null:wallet} onChange={()=>refresh()}/><section className="card"><h2>{t.account}</h2><div className="data-row"><span>USD</span><b>{money(demo?0:balance)}</b></div><p>{t.risk}</p><button disabled={busy||demo||!wallet||!config.deployed} className="button" onClick={()=>run(()=>tx('faucet',[],true))}>{t.faucet}<ArrowUpRight size={16}/></button><p style={{marginTop:20}}>MON: <a className="text-link accent" target="_blank" rel="noreferrer" href="https://faucet.monad.xyz">faucet.monad.xyz ↗</a></p></section></div>}
 {tab==='review'&&isAdmin&&<section className="card"><h2>{t.review}</h2><button disabled={busy} className="button" onClick={()=>run(async()=>{setAdminData(await signedApi(wallet!,'adminRead'))})}>{t.refresh}</button><label>{t.reviewNote}</label><textarea value={reviewNote} onChange={e=>setReviewNote(e.target.value)}/><h3 style={{marginTop:30}}>{t.join}</h3>{adminData.applications.map((a:any)=><div className="data-row" key={a.wallet}><div><b>{a.name}</b><small>{short(a.wallet)} · {t[a.status as 'pending']}</small><a target="_blank" rel="noreferrer" href={a.profile}>{t.profile} ↗</a><p>{a.note}</p></div><div className="form-actions"><button className="button small lime" disabled={busy||a.status==='approved'} onClick={()=>run(async()=>{const id=keccak256(toBytes('DANK-member:'+a.wallet.toLowerCase()));if(await read('memberOf',[a.wallet])===ZERO)await tx('enroll',[id,a.wallet]);await signedApi(wallet!,'review',{kind:'application',wallet:a.wallet,status:'approved'});setAdminData(await signedApi(wallet!,'adminRead'))})}>{t.approve}</button><button disabled={busy} className="button small" onClick={()=>run(async()=>{await signedApi(wallet!,'review',{kind:'application',wallet:a.wallet,status:'rejected'});setAdminData(await signedApi(wallet!,'adminRead'))})}>{t.reject}</button></div></div>)}<h3 style={{marginTop:30}}>{t.achievements}</h3>{adminData.evidence.map((e:any)=><div className="data-row" key={e.id}><div><b>{e.title}</b><small>{short(e.wallet)} / {e.placement===1?20:e.placement===2?10:e.placement===3?5:1} pts / {t[e.status as 'pending']}</small><a href={e.proof} target="_blank" rel="noreferrer">{t.proof} ↗</a><p>{e.note}</p></div><button className="button small lime" disabled={busy||e.status==='approved'||!reviewNote.trim()} onClick={()=>run(async()=>{const id=await read('memberOf',[e.wallet]);if(id===ZERO)throw new Error(t.memberOnly);const evidenceId=keccak256(toBytes('DANK:'+id+':'+e.event_slug));if(!await read('usedEvidence',[evidenceId]))await tx('verifyAchievement',[id,evidenceId,e.placement??0]);const m=await read('members',[id]);const score=Number(m[1]);const limit=score>=40?500:score>=20?200:80;await tx('setLimits',[id,units(limit),units(Math.max(limit,display(m[4])))]);await signedApi(wallet!,'review',{kind:'evidence',id:e.id,status:'approved',note:reviewNote});setAdminData(await signedApi(wallet!,'adminRead'))})}>{t.approve}</button></div>)}</section>}
 {hash&&<div className="notice"><a href={config.explorer+'/tx/'+hash} target="_blank" rel="noreferrer">{t.transaction}: {short(hash)} ↗</a></div>}{busy&&<div className="banner" role="status">{t.pendingTx}</div>}
 </main><Footer/>{toast&&<div role="status" className="toast">{toast}</div>}</>
}
