// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;
import '../src/Dank.sol';
import '../src/TestUSD.sol';
interface Vm {function warp(uint256) external;function prank(address) external;function startPrank(address) external;function stopPrank() external;function expectRevert() external;}
contract DankTest {
 Vm constant vm=Vm(address(uint160(uint256(keccak256('hevm cheat code')))));
 Dank d;TestUSD t;address a=address(11);address g=address(12);address b=address(13);bytes32 A=keccak256('A');bytes32 G=keccak256('G');bytes32 B=keccak256('B');
 function setUp() public {vm.warp(1790416800);t=new TestUSD();d=new Dank(address(t),address(this));d.enroll(A,a);d.enroll(G,g);d.enroll(B,b);d.enroll(keccak256('admin'),address(this));d.verifyAchievement(A,keccak256('a-win'),1);d.verifyAchievement(G,keccak256('g-win1'),1);d.verifyAchievement(G,keccak256('g-win2'),1);d.verifyAchievement(B,keccak256('b-win'),1);d.setLimits(A,1000e6,1000e6);d.setLimits(G,1000e6,1000e6);d.setLimits(B,1000e6,1000e6);t.faucet();t.approve(address(d),type(uint256).max);d.depositCapital(10000e6);d.startLending();}
 function open(uint256 n) internal returns(uint256 id){vm.prank(a);id=d.requestLoan(200e6,n);vm.prank(g);d.guarantee(id,200e6);vm.prank(a);d.activate(id);}
 function testLifecycle() public {uint256 id=open(12);require(t.balanceOf(a)==200e6);uint256 quote=d.payoff(id);require(quote==200e6);vm.startPrank(a);t.approve(address(d),type(uint256).max);d.repayAll(id,quote);vm.stopPrank();require(d.canBorrow(A));require(d.outstandingPrincipal()==0);d.settleCohort();d.claimCapital();require(t.balanceOf(address(this))==10000e6);}
 function testOverdueBlocksGuarantorWithoutKeeper() public {uint256 id=open(1);Dank.Installment[] memory s=d.getSchedule(id);vm.warp(s[0].due+3 days+1);require(!d.canBorrow(G));vm.startPrank(g);vm.expectRevert();d.requestLoan(20e6,1);vm.stopPrank();}
 function testPauseStillAllowsRepayment() public {uint256 id=open(1);d.setPaused(true);vm.startPrank(a);t.approve(address(d),type(uint256).max);d.repayAll(id,d.payoff(id));vm.stopPrank();require(d.outstandingPrincipal()==0);}
 function testCannotDoubleActivate() public {uint256 id=open(1);vm.startPrank(a);vm.expectRevert();d.activate(id);vm.stopPrank();}
 function testNoSelfGuarantee() public {vm.prank(a);uint256 id=d.requestLoan(100e6,1);vm.startPrank(a);vm.expectRevert();d.guarantee(id,100e6);vm.stopPrank();}
 function testCannotBorrowWithoutMembership() public {vm.startPrank(address(99));vm.expectRevert();d.requestLoan(100e6,1);vm.stopPrank();}
 function testEvidenceReplay() public {vm.expectRevert();d.verifyAchievement(A,keccak256('a-win'),1);}
 function testExpiryReleasesCapacity() public {vm.prank(a);uint256 id=d.requestLoan(200e6,1);vm.prank(g);d.guarantee(id,200e6);vm.warp(block.timestamp+8 days);d.cancelRequest(id);require(d.getBackings(G).length==0);require(d.canBorrow(A));}
 function testWalletRotationPreservesLoan() public {uint256 id=open(1);vm.prank(a);d.proposeWallet(address(100));vm.prank(address(100));d.acceptWallet(A);require(d.memberOf(a)==0&&d.memberOf(address(100))==A);require(!d.canBorrow(A));vm.startPrank(a);vm.expectRevert();d.requestLoan(50e6,1);vm.stopPrank();require(d.payoff(id)==200e6);}
 function testDefaultIdempotentAndNotErasedByRepayment() public {uint256 id=open(1);Dank.Installment[] memory s=d.getSchedule(id);vm.warp(s[0].due+31 days);d.recordDefault(id);d.recordDefault(id);(,,,,,,uint256 strikes,)=d.members(G);require(strikes==1);vm.startPrank(a);t.faucet();t.approve(address(d),type(uint256).max);d.repayAll(id,d.payoff(id));vm.stopPrank();require(!d.canBorrow(G));}
 function testPartialPaymentsDoNotResetPenaltyClock() public {uint256 id=open(1);Dank.Installment[] memory s=d.getSchedule(id);vm.warp(s[0].due+10 days+12 hours);uint256 before_=d.dueNow(id);vm.startPrank(a);t.faucet();t.approve(address(d),type(uint256).max);d.repay(id,1);vm.stopPrank();require(d.dueNow(id)==before_-1);vm.warp(s[0].due+11 days);require(d.dueNow(id)>before_);}
 function testUnauthorizedLossAndAdmin() public {uint256 id=open(1);vm.startPrank(a);vm.expectRevert();d.recognizeLoss(id);vm.expectRevert();d.setLimits(A,1000e6,1000e6);vm.stopPrank();}
 function testLossRecoveryGoesToOriginalCapital() public {uint256 id=open(1);Dank.Installment[] memory s=d.getSchedule(id);vm.warp(s[0].due+91 days);d.recognizeLoss(id);d.settleCohort();d.claimCapital();require(t.balanceOf(address(this))==9800e6);vm.startPrank(a);t.faucet();t.approve(address(d),type(uint256).max);uint256 quote=d.payoff(id);d.repayAll(id,quote);vm.stopPrank();d.claimCapital();require(t.balanceOf(address(this))==9800e6+quote);}
 function testFuzzAmortization(uint96 raw,uint8 term) public {uint256 amount=10e6+uint256(raw)%190000001;uint256 months_=1+uint256(term)%12;vm.prank(a);uint256 id=d.requestLoan(amount,months_);vm.prank(g);d.guarantee(id,amount);vm.prank(a);d.activate(id);Dank.Installment[] memory s=d.getSchedule(id);uint256 sum;uint256 last;for(uint256 i;i<s.length;i++){sum+=s[i].principal;require(s[i].due>last);last=s[i].due;}require(sum==amount);}
 function testCalendarEndOfMonth() public pure {require(Calendar.addMonths(1706659200,1)==1709164800);require(Calendar.addMonths(1706659200,2)==1711843200);}
 function testFiveWinsOnlyTwentyPoints() public {for(uint256 i;i<5;i++)d.verifyAchievement(A,keccak256(abi.encode("extra-win",i)),1);(,uint256 score,,,,,,)=d.members(A);require(score==20&&d.hackathonScore(A)==20);}
 function testFirstPodiumLocksScoreAndNoStacking() public {bytes32 id=keccak256('new');d.enroll(id,address(555));d.verifyAchievement(id,keccak256('participation'),0);require(d.hackathonScore(id)==1);d.verifyAchievement(id,keccak256('third'),3);require(d.hackathonScore(id)==5);d.verifyAchievement(id,keccak256('second'),2);require(d.hackathonScore(id)==5);d.verifyAchievement(id,keccak256('first'),1);d.verifyAchievement(id,keccak256('later-participation'),0);(,uint256 score,,,,,,)=d.members(id);require(score==5);}
 function testInvalidRankAndUnauthorizedScoring() public {vm.expectRevert();d.verifyAchievement(A,keccak256('invalid'),4);vm.startPrank(a);vm.expectRevert();d.verifyAchievement(A,keccak256('forged'),1);vm.stopPrank();}
 function testMigrationCannotRestartHackathonPoints() public {vm.prank(a);d.proposeWallet(address(100));vm.prank(address(100));d.acceptWallet(A);d.verifyAchievement(A,keccak256('new-wallet-win'),1);(,uint256 score,,,,,,)=d.members(A);require(score==20);}
 function testWalletScoreCapAndReplacement() public {d.updateWalletScore(A,80,keccak256('snapshot1'),block.timestamp+7 days);(,uint256 score,,,,,,)=d.members(A);require(score==100);d.updateWalletScore(A,10,keccak256('snapshot2'),block.timestamp+7 days);(,score,,,,,,)=d.members(A);require(score==30);vm.expectRevert();d.updateWalletScore(A,81,keccak256('overflow'),block.timestamp+7 days);vm.expectRevert();d.updateWalletScore(A,10,keccak256('snapshot2'),block.timestamp+7 days);}
 function testExpiredAssessmentStopsNewBorrowing() public {d.updateWalletScore(A,10,keccak256('expiry'),block.timestamp+1 days);vm.warp(block.timestamp+1 days+1);require(!d.canBorrow(A));vm.startPrank(a);vm.expectRevert();d.requestLoan(10e6,1);vm.stopPrank();}
 function testWalletScoreCannotClearDefault() public {uint256 id=open(1);Dank.Installment[] memory s=d.getSchedule(id);vm.warp(s[0].due+31 days);d.recordDefault(id);d.updateWalletScore(G,80,keccak256('recovered'),block.timestamp+7 days);require(!d.canBorrow(G));}
 function testPublicRegistrationAndStarterLoan() public {address newcomer=address(900);vm.prank(newcomer);bytes32 id=d.register();(,uint256 score,uint256 limit,,,,,)=d.members(id);require(score==0&&limit==80e6);vm.prank(newcomer);uint256 loan=d.requestLoan(80e6,1);vm.prank(g);d.guarantee(loan,80e6);vm.prank(newcomer);d.activate(loan);require(t.balanceOf(newcomer)==80e6);vm.startPrank(newcomer);vm.expectRevert();d.register();vm.stopPrank();}
 function testRotationCannotReclaimStarterIdentity() public {vm.prank(address(901));bytes32 id=d.register();vm.prank(address(901));d.proposeWallet(address(902));vm.prank(address(902));d.acceptWallet(id);vm.startPrank(address(901));vm.expectRevert();d.register();vm.stopPrank();}
}
