'use client';
import {useState} from 'react';
import {ArrowRight,Wallet,ShieldCheck,Landmark,Layers,CheckCircle2,LockKeyhole,Database,Link2,Clock3} from 'lucide-react';
import {useLanguage} from './shell';
import {scoreCopy} from '@/lib/score-copy';
import {docsCopy} from '@/lib/docs-copy';
import {supportAllocation} from '@/lib/support';
import {CAPS} from '@/lib/scoring';
const copy={
 tr:{example:'Açıklayıcı örnek · canlı hesap verisi değildir',flow:'Krediye giden yol',wallet:'Cüzdan geçmişi',defi:'DeFi kullanımı',repayment:'Geri ödeme davranışı',optional:'İsteğe bağlı kanıt',total:'Toplam puan tavanı',caps:'Kategori tavanları',once:'İlk derece bir kez sayılır',later:'Sonraki dereceler',participation:'Katılım',try:'Kefalet hesabını dene',assigned:'Örnekte tanımlı toplam kapasite',used:'Daha önce ayrılan destek',needed:'Kredinin eksik desteği',minimum:'En düşük tutar uygulanır',approve:'Kefaleti onayla',cash:'Cüzdandan para çekilmez',request:'Kredi isteği',back:'Kefalet',activate:'Etkinleştirme',pay:'Geri ödeme',release:'Kapasite serbest',expires:'7 gün geçerli',covered:'Anapara tamamen desteklenir',terms:'1–12 ay · yıllık %15',done:'Kredi kapanır',capital:'İlk havuz fonlaması',fund:'Fon toplama',lend:'Kredi verme',settle:'Hesaplaşma',current:'Mevcut aşama',loss:'Ödenmeyen anapara havuz kaybıdır',admin:'Yönetici',member:'Üye',adminRights:'Kanıt doğrulama, puan ve limit güncelleme, duraklatma',memberRights:'Cüzdan imzası, kredi talebi, kefalet ve geri ödeme',test:'Yalnızca testnet',notReady:'Mainnet açılışı ve bağımsız denetim tamamlanmadı',data:'Doğrulanmış veri',assessment:'Puan değerlendirmesi',limit:'Kredi limiti',missing:'Eksik veri puan üretmez',app:'Uygulama',protocol:'Kredi sözleşmesi',token:'Test USD',store:'Kanıt kayıtları',offchain:'Zincir dışı',onchain:'Monad testnet',points:'puan'},
 en:{example:'Illustration · not live account data',flow:'The path to credit',wallet:'Wallet history',defi:'DeFi activity',repayment:'Repayment behavior',optional:'Optional evidence',total:'Total score ceiling',caps:'Category ceilings',once:'First podium counts once',later:'Later podiums',participation:'Participation',try:'Explore support allocation',assigned:'Assigned capacity in this example',used:'Existing commitments',needed:'Uncovered loan amount',minimum:'The lowest amount applies',approve:'Approve the guarantee',cash:'No wallet funds are withdrawn',request:'Loan request',back:'Guarantee',activate:'Activation',pay:'Repayment',release:'Capacity released',expires:'Valid for 7 days',covered:'Principal fully supported',terms:'1–12 months · 15% APR',done:'Loan closes',capital:'Initial pool funding',fund:'Funding',lend:'Lending',settle:'Settlement',current:'Current phase',loss:'Unpaid principal is a pool loss',admin:'Administrator',member:'Member',adminRights:'Verify evidence, update scores and limits, pause activity',memberRights:'Wallet signatures, loan requests, guarantees and repayment',test:'Testnet only',notReady:'Mainnet launch and independent audit are not complete',data:'Verified data',assessment:'Score assessment',limit:'Credit limit',missing:'Missing data earns no points',app:'Application',protocol:'Credit contract',token:'Test USD',store:'Evidence records',offchain:'Offchain',onchain:'Monad testnet',points:'points'},
 de:{example:'Beispiel · keine aktuellen Kontodaten',flow:'Der Weg zum Kredit',wallet:'Wallet-Verlauf',defi:'DeFi-Aktivität',repayment:'Rückzahlungsverhalten',optional:'Optionale Nachweise',total:'Maximale Gesamtpunktzahl',caps:'Kategoriegrenzen',once:'Erster Podiumsplatz zählt einmal',later:'Spätere Podiumsplätze',participation:'Teilnahme',try:'Unterstützung berechnen',assigned:'Zugewiesene Kapazität im Beispiel',used:'Bestehende Zusagen',needed:'Fehlende Kreditdeckung',minimum:'Der niedrigste Betrag gilt',approve:'Bürgschaft bestätigen',cash:'Keine Abbuchung aus der Wallet',request:'Kreditantrag',back:'Bürgschaft',activate:'Aktivierung',pay:'Rückzahlung',release:'Kapazität freigegeben',expires:'7 Tage gültig',covered:'Kapital vollständig gedeckt',terms:'1–12 Monate · 15 % Jahreszins',done:'Kredit abgeschlossen',capital:'Anfängliche Poolfinanzierung',fund:'Finanzierung',lend:'Kreditvergabe',settle:'Abrechnung',current:'Aktuelle Phase',loss:'Unbezahltes Kapital ist ein Poolverlust',admin:'Administrator',member:'Mitglied',adminRights:'Nachweise prüfen, Scores und Limits ändern, pausieren',memberRights:'Wallet-Signaturen, Kreditanträge, Bürgschaften und Rückzahlung',test:'Nur Testnet',notReady:'Mainnet-Start und unabhängiges Audit stehen aus',data:'Bestätigte Daten',assessment:'Scorebewertung',limit:'Kreditlimit',missing:'Fehlende Daten bringen keine Punkte',app:'Anwendung',protocol:'Kreditvertrag',token:'Test-USD',store:'Nachweise',offchain:'Außerhalb der Blockchain',onchain:'Monad-Testnet',points:'Punkte'},
 es:{example:'Ejemplo · no son datos de una cuenta real',flow:'El camino al crédito',wallet:'Historial de cartera',defi:'Actividad DeFi',repayment:'Comportamiento de pago',optional:'Pruebas opcionales',total:'Puntuación máxima total',caps:'Topes por categoría',once:'El primer podio cuenta una vez',later:'Podios posteriores',participation:'Participación',try:'Explora el cálculo del respaldo',assigned:'Capacidad asignada en este ejemplo',used:'Compromisos existentes',needed:'Importe sin respaldo',minimum:'Se aplica el importe menor',approve:'Aprobar la garantía',cash:'No se retiran fondos de la cartera',request:'Solicitud',back:'Garantía',activate:'Activación',pay:'Devolución',release:'Capacidad liberada',expires:'Válida durante 7 días',covered:'Principal totalmente respaldado',terms:'1–12 meses · 15 % anual',done:'Préstamo cerrado',capital:'Financiación inicial del fondo',fund:'Financiación',lend:'Préstamos',settle:'Liquidación',current:'Fase actual',loss:'El principal impagado es una pérdida del fondo',admin:'Administrador',member:'Miembro',adminRights:'Verifica pruebas, actualiza puntuaciones y límites, pausa operaciones',memberRights:'Firmas, solicitudes, garantías y pagos',test:'Solo testnet',notReady:'El lanzamiento mainnet y la auditoría independiente siguen pendientes',data:'Datos verificados',assessment:'Evaluación',limit:'Límite de crédito',missing:'Los datos ausentes no suman puntos',app:'Aplicación',protocol:'Contrato de crédito',token:'USD de prueba',store:'Registro de pruebas',offchain:'Fuera de cadena',onchain:'Testnet Monad',points:'puntos'},
 fr:{example:'Exemple · aucune donnée de compte en direct',flow:'Le chemin vers le crédit',wallet:'Historique du portefeuille',defi:'Activité DeFi',repayment:'Comportement de paiement',optional:'Preuves facultatives',total:'Plafond total du score',caps:'Plafonds par catégorie',once:'Le premier podium compte une fois',later:'Podiums suivants',participation:'Participation',try:'Explorer le calcul du soutien',assigned:'Capacité attribuée dans cet exemple',used:'Engagements existants',needed:'Montant restant à couvrir',minimum:'Le montant le plus faible s’applique',approve:'Approuver la garantie',cash:'Aucun prélèvement sur le portefeuille',request:'Demande',back:'Garantie',activate:'Activation',pay:'Remboursement',release:'Capacité libérée',expires:'Valable 7 jours',covered:'Capital intégralement couvert',terms:'1–12 mois · 15 % annuel',done:'Prêt clôturé',capital:'Financement initial du fonds',fund:'Collecte',lend:'Prêts',settle:'Règlement',current:'Phase actuelle',loss:'Le capital impayé est une perte du fonds',admin:'Administrateur',member:'Membre',adminRights:'Vérification des preuves, scores et limites, suspension',memberRights:'Signatures, demandes, garanties et remboursements',test:'Testnet uniquement',notReady:'Lancement mainnet et audit indépendant non terminés',data:'Données vérifiées',assessment:'Évaluation du score',limit:'Limite de crédit',missing:'Les données absentes ne donnent aucun point',app:'Application',protocol:'Contrat de crédit',token:'USD de test',store:'Registre des preuves',offchain:'Hors chaîne',onchain:'Testnet Monad',points:'points'}
};
export function DocsVisuals({topic}:{topic:string}){
 const {lang,t}=useLanguage();const c=copy[lang],d=docsCopy[lang],s=scoreCopy[lang];const [score,setScore]=useState(80),[used,setUsed]=useState(100),[need,setNeed]=useState(150);
 const result=supportAllocation(score,500000000n,BigInt(used)*1000000n,BigInt(need)*1000000n);
 const money=(v:number)=>new Intl.NumberFormat(lang).format(v);
 const flow=(labels:string[],icons=[Wallet,ShieldCheck,Landmark])=><div className="dv-flow">{labels.map((label,i)=>{const Icon=icons[i%icons.length];return <div className="dv-flow-item" key={label}><div className="dv-node"><Icon size={23}/><strong>{label}</strong></div>{i<labels.length-1&&<ArrowRight className="dv-arrow" size={18}/>}</div>})}</div>;
 return <div className="docs-visuals">
 {topic==='introduction'&&<><figure className="dv-panel"><figcaption>{c.flow}</figcaption>{flow([t.profile,t.guarantees,d.life])}<div className="dv-stat-row"><div><b>100</b><span>{c.total}</span></div><div><b>USD</b><span>{c.token}</span></div><div><b>MON</b><span>Gas · Monad</span></div></div></figure><div className="dv-cards">{[[Wallet,c.wallet],[Layers,c.defi],[CheckCircle2,c.repayment]].map(([Icon,label])=>{const Glyph=Icon as typeof Wallet;return <div className="dv-small-card" key={String(label)}><Glyph size={22}/><strong>{String(label)}</strong></div>})}</div></>}
 {topic==='profile'&&<><figure className="dv-panel"><figcaption>{t.profile}</figcaption>{flow([c.data,c.assessment,c.limit],[Database,Layers,Wallet])}<div className="dv-callout"><LockKeyhole size={20}/><span>{c.missing}</span></div></figure><div className="dv-cards"><div className="dv-small-card"><Wallet/><strong>80 USD</strong><span>{t.network}</span></div><div className="dv-small-card"><ShieldCheck/><strong>0 USD</strong><span>{d.available}</span></div></div><p className="dv-caption">{t.publicNotice}</p></>}
 {topic==='scoring'&&<><figure className="dv-panel"><figcaption>{c.total}</figcaption><div className="dv-score-total"><b>100</b><span>{c.points}</span></div><div className="dv-stack"><div style={{flex:80}}>80</div><div style={{flex:20}}>20</div></div><div className="dv-legend"><span>80 · {c.wallet} / DeFi</span><span>20 · {c.optional}</span></div><div className="dv-bars">{s.rows.map((label,i)=>{const cap=Object.values(CAPS).slice(1)[i];return <div key={label}><div><span>{label}</span><b>{cap}</b></div><meter min={0} max={20} value={cap} aria-label={label}/></div>})}</div><p className="dv-caption">{c.caps} · {s.missing}</p></figure><figure className="dv-panel"><figcaption>{c.once}</figcaption><div className="dv-podium">{[20,10,5].map((n,i)=><div key={n}><span>#{i+1}</span><b>+{n}</b><div style={{height:80-i*22}}/></div>)}</div><div className="dv-legend"><span>{c.participation}: +1</span><span>{c.later}: +0</span></div><p className="dv-caption">{s.rule}</p></figure></>}
 {(topic==='limits'||topic==='guarantees')&&<><figure className="dv-panel"><figcaption>{c.try}</figcaption><p className="dv-caption">{c.example}</p><p className="dv-caption">{t.score} &lt; 80 → 0 USD</p><div className="dv-tiers">{[[80,89,80],[90,94,200],[95,100,500]].map(([low,high,cap])=><div key={low} className={score>=low&&score<=high?'selected':''}><span>{low}–{high} {c.points}</span><b>{cap} USD</b></div>)}</div><label className="dv-slider">{t.score}<output>{score}</output><input type="range" min={0} max={100} value={score} onChange={e=>setScore(Number(e.target.value))}/></label><label className="dv-slider">{c.used}<output>{used} USD</output><input type="range" min={0} max={500} step={10} value={used} onChange={e=>setUsed(Number(e.target.value))}/></label><label className="dv-slider">{c.needed}<output>{need} USD</output><input type="range" min={0} max={500} step={10} value={need} onChange={e=>setNeed(Number(e.target.value))}/></label><p className="dv-caption">{c.assigned}: 500 USD</p><div className="dv-equation"><span>{Number(result.scoreCap)/1e6} USD</span><span>{500-used} USD</span><span>{need} USD</span><ArrowRight size={18}/><strong aria-live="polite">{Number(result.amount)/1e6} USD</strong></div><p className="dv-caption">{c.minimum} · {d.automatic}</p></figure>{topic==='guarantees'&&<figure className="dv-panel"><figcaption>{t.guarantees}</figcaption>{flow([d.allocated,c.approve,c.release],[Layers,ShieldCheck,CheckCircle2])}<div className="dv-callout"><LockKeyhole size={20}/>{c.cash}</div></figure>}</>}
 {topic==='lifecycle'&&<figure className="dv-panel"><figcaption>{d.life}</figcaption><ol className="dv-timeline">{[[c.request,c.expires],[c.back,c.covered],[c.activate,'USD → '+c.member],[c.pay,c.terms],[c.release,c.done]].map(([title,sub],i)=><li key={title}><span className="dv-step">{String(i+1).padStart(2,'0')}</span><div><strong>{title}</strong><p>{sub}</p></div>{i===4?<CheckCircle2 size={20}/>:<Clock3 size={20}/>}</li>)}</ol></figure>}
 {topic==='capital'&&<><figure className="dv-panel"><figcaption>{c.capital}</figcaption><div className="dv-fund"><Landmark size={34}/><b>{money(50000)}<small> TEST USD</small></b></div><div className="dv-phases">{[c.fund,c.lend,c.settle].map((label,i)=><div key={label} className={i===1?'selected':''}><span>0{i+1}</span><strong>{label}</strong>{i===1&&<small>{c.current}</small>}</div>)}</div>{flow([t.pool,c.member,c.pay],[Landmark,Wallet,ArrowRight])}<div className="dv-callout"><ShieldCheck size={20}/>{c.loss}</div></figure><p className="dv-caption">{c.capital} · {t.risk}</p></>}
 {topic==='security'&&<><div className="dv-cards"><div className="dv-small-card"><Wallet/><strong>{c.member}</strong><p>{c.memberRights}</p></div><div className="dv-small-card"><LockKeyhole/><strong>{c.admin}</strong><p>{c.adminRights}</p></div></div><figure className="dv-panel"><figcaption>{c.test}</figcaption><div className="dv-callout"><ShieldCheck size={24}/><span>{c.notReady}</span></div><p>{c.loss}</p></figure></>}
 {topic==='contracts'&&<figure className="dv-panel"><figcaption>{d.contracts}</figcaption><div className="dv-network"><div className="dv-network-lane"><span>{c.offchain}</span>{flow([c.app,c.store],[Wallet,Database])}</div><div className="dv-network-bridge"><Link2 size={22}/><span>RPC · 10143</span></div><div className="dv-network-lane"><span>{c.onchain}</span>{flow([c.protocol,c.token],[ShieldCheck,Layers])}</div></div><p className="dv-caption">{c.test} · MON / Gas · USD / {c.token}</p></figure>}
 </div>
}
