'use client';
import {useEffect,useState} from 'react';
import {type Address} from 'viem';
import {config,read,write,units,display} from '@/lib/chain';
import {useLanguage} from './shell';
import {liquidityCopy} from '@/lib/liquidity-copy';
export function LiquidityPanel({wallet,onChange}:{wallet:Address|null;onChange:()=>Promise<void>}){
 const {lang,t}=useLanguage(),c=liquidityCopy[lang];const [amount,setAmount]=useState('10000'),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[hash,setHash]=useState('');
 const [snapshot,setSnapshot]=useState<{assets:bigint;total:bigint;shares:bigint;policy:string;accepted:boolean;phase:number;paused:boolean}|null>(null);
 async function refresh(){const [assets,total,policy,phase,paused]=await Promise.all([read('poolAssets'),read('totalShares'),read('RISK_POLICY'),read('phase'),read('paused')]);const [shares,accepted]=wallet?await Promise.all([read('shares',[wallet]),read('acceptedRisk',[wallet])]):[0n,''];setSnapshot({assets,total,policy,phase:Number(phase),paused,shares,accepted:accepted===policy})}
 useEffect(()=>{setSnapshot(null);setConsent(false);setError('');void refresh().catch(()=>setError(t.error))},[wallet]);
 let input=0n;try{if(/^\d+(\.\d{0,6})?$/.test(amount))input=units(amount)}catch{}
 const minted=snapshot?input*(snapshot.total+1000000n)/(snapshot.assets+1n):0n;
 const percent=(a:bigint,b:bigint)=>b?new Intl.NumberFormat(lang,{maximumFractionDigits:4}).format(Number(a*1000000n/b)/10000)+'%':'0%';
 async function act(kind:'risk'|'deposit'|'claim'){if(!wallet||!snapshot||busy)return;setBusy(true);setError('');try{let h;if(kind==='risk'){if(!consent)throw new Error(c.accept);h=await write(wallet,'acceptRisk',[snapshot.policy])}else if(kind==='deposit'){if(input<=0n)throw new Error(t.amount);const quote:bigint=await read('previewDeposit',[input]);if(quote===0n)throw new Error(t.amount);await write(wallet,'approve',[config.protocol,input],true);h=await write(wallet,'depositCapitalWithMinShares',[input,quote*995n/1000n])}else h=await write(wallet,'claimCapital');setHash(h);await refresh();await onChange()}catch(e){setError((e as Error).message.slice(0,220))}finally{setBusy(false)}}
 return <section className="card"><h2>{c.title}</h2><p>{c.lead}</p><div className="data-row"><span>{c.assets}</span><b>{snapshot?display(snapshot.assets).toLocaleString(lang):'—'} USD</b></div><div className="data-row"><span>{c.share}</span><b>{snapshot?percent(snapshot.shares,snapshot.total):'—'}</b></div><label htmlFor="lp-amount">{t.amount} · USD</label><input id="lp-amount" type="number" min="0.000001" step="0.000001" value={amount} onChange={e=>setAmount(e.target.value)}/><div className="data-row"><span>{c.after}</span><b>{snapshot&&input>0n?percent(snapshot.shares+minted,snapshot.total+minted):'—'}</b></div><small>{c.preview}</small><div className="notice" style={{marginTop:20}}><p>{c.terms}</p><small>{c.policy}</small></div>{!snapshot?.accepted?<><label style={{display:'flex',alignItems:'flex-start',gap:10}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>{c.accept}</label><button className="button" disabled={busy||!wallet||!snapshot||!consent} onClick={()=>act('risk')}>{c.sign}</button></>:<p className="accent">✓ {c.signed}</p>}<div className="form-actions"><button className="button lime" disabled={busy||!wallet||!snapshot?.accepted||snapshot.paused||snapshot.phase===2||input<=0n} onClick={()=>act('deposit')}>{busy?t.loading:t.deposit}</button><button className="button" disabled={busy||!wallet||snapshot?.phase!==2} onClick={()=>act('claim')}>{t.withdraw}</button></div><p><small>{c.withdraw}</small></p>{error&&<p role="alert" className="danger-text">{error}</p>}{hash&&<a className="text-link" href={config.explorer+'/tx/'+hash} target="_blank" rel="noreferrer">{t.success} ↗</a>}</section>
}
