'use client';
import {createContext,useContext,useEffect,useState} from 'react';
import {dashboardCopy} from '@/lib/dashboard-copy';
import {copies,languages,type Lang} from '@/lib/i18n';
import {ArrowUpRight,Sun,Moon,Globe} from 'lucide-react';
const C=createContext({lang:'en' as Lang,t:copies.en,setLang:(_:Lang)=>{}});
export const useLanguage=()=>useContext(C);
export function Providers({children}:{children:React.ReactNode}){const[lang,set]=useState<Lang>('en');useEffect(()=>{const saved=localStorage.getItem('dank-language') as Lang;if(saved in languages){set(saved);return}fetch('/api/locale').then(r=>r.json()).then((d:any)=>{if(d.language in languages)set(d.language)}).catch(()=>{const l=navigator.language.split('-')[0] as Lang;if(l in languages)set(l)})},[]);useEffect(()=>{document.documentElement.lang=lang},[lang]);return <C.Provider value={{lang,t:copies[lang],setLang:l=>{set(l);localStorage.setItem('dank-language',l)}}}>{children}</C.Provider>}
export function Logo(){return <a href="/" className="logo" aria-label="DANK home"><span className="logo-mark"><i/><i/><i/></span>DANK<span className="logo-period">.</span></a>}
export function Header(){const{lang,t,setLang}=useLanguage();const[dark,setDark]=useState(true);useEffect(()=>{const isDark=localStorage.getItem('dank-theme')!=='light';setDark(isDark);document.documentElement.dataset.theme=isDark?'dark':'light'},[]);return <header className="header"><Logo/><nav><a href="/#how">{t.navHow}</a><a href="/docs">{t.navDocs}</a><a href="/dashboard">{dashboardCopy[lang].title}</a></nav><div className="header-right"><label className="locale"><Globe size={15}/><select aria-label={t.language} value={lang} onChange={e=>setLang(e.target.value as Lang)}>{Object.entries(languages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><button className="icon-button" aria-label={t.theme} onClick={()=>{setDark(!dark);document.documentElement.dataset.theme=dark?'light':'dark';localStorage.setItem('dank-theme',dark?'light':'dark')}}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button><a className="button small lime" href="/app">{t.enter}<ArrowUpRight size={16}/></a></div></header>}
export function Footer(){const{t,lang}=useLanguage();return <footer><Logo/><span>{t.footer}</span><a href="/dashboard">{dashboardCopy[lang].title}</a><small>{t.risk}</small></footer>}
