import {createPublicClient,createWalletClient,custom,http,parseAbi,parseUnits,formatUnits,type Address,type Abi,type EIP1193Provider} from 'viem';
import {monadTestnet} from 'viem/chains';
import deployment from './deployment.json';
const config: {chainId:number;rpc:string;explorer:string;protocol:Address|null;token:Address|null;admin:string;tokenSymbol:string;deployed:boolean}={...deployment,protocol:deployment.protocol as Address|null,token:deployment.token as Address|null};
import abi from './protocol-abi.json';
export {config,abi};
export const publicClient=createPublicClient({chain:monadTestnet,batch:{multicall:{wait:20,batchSize:8192}},transport:http(config.rpc,{timeout:15000})});
export const tokenAbi=parseAbi(['function balanceOf(address) view returns (uint256)','function approve(address,uint256) returns (bool)','function faucet()']);
export const units=(v:number|string)=>parseUnits(String(v),6);
export const display=(v:bigint)=>Number(formatUnits(v,6));
export const short=(v:string)=>v.slice(0,6)+'…'+v.slice(-4);
export function provider():EIP1193Provider|undefined{return (window as unknown as {ethereum?:EIP1193Provider}).ethereum}
export async function connectWallet(){const p=provider();if(!p)throw new Error('WALLET_MISSING');const w=createWalletClient({chain:monadTestnet,transport:custom(p)});const [address]=await w.requestAddresses();return address;}
export async function ensureNetwork(){const p=provider();if(!p)throw new Error('WALLET_MISSING');try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId:'0x279f'}]})}catch(e){if((e as {code:number}).code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId:'0x279f',chainName:'Monad Testnet',nativeCurrency:{name:'MON',symbol:'MON',decimals:18},rpcUrls:[config.rpc],blockExplorerUrls:[config.explorer]}]})}}
export async function read(fn:string,args:unknown[]=[]){if(!config.protocol)throw new Error('NOT_DEPLOYED');return publicClient.readContract({address:config.protocol as Address,abi,functionName:fn,args}) as Promise<any>}
export async function write(address:Address,fn:string,args:unknown[]=[],token=false){if(!config.protocol||!config.token)throw new Error('NOT_DEPLOYED');await ensureNetwork();const p=provider();if(!p)throw new Error('WALLET_MISSING');const wallet=createWalletClient({chain:monadTestnet,transport:custom(p)});const req={address:(token?config.token:config.protocol) as Address,abi:(token?tokenAbi:abi) as Abi,functionName:fn,args,account:address};const simulation=await publicClient.simulateContract(req);const hash=await wallet.writeContract(simulation.request);const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success')throw new Error('TRANSACTION_REVERTED');return hash;}
export async function signedApi(wallet:Address,action:string,data:Record<string,unknown>={}){const p=provider();if(!p)throw new Error('WALLET_MISSING');const challenge=await fetch('/api/challenge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wallet,action,data})});const c:any=await challenge.json();if(!challenge.ok)throw new Error(c.error||'AUTH_FAILED');const w=createWalletClient({transport:custom(p)});const signature=await w.signMessage({account:wallet,message:c.message});const r=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wallet,action,data,id:c.id,signature})});const result:any=await r.json();if(!r.ok)throw new Error(result.error||'REQUEST_FAILED');return result;}
